name: GitHub Actions - CD
run-name: "${{ github.actor }} merged into main 🚀"
on:
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  contents: read

jobs:
  zip-src:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Disponibiliza Zip Atualizado
        uses: actions/upload-artifact@v7
        with:
          name: src-${{ github.event.pull_request.merge_commit_sha }}
          path: src/
          if-no-files-found: error
          retention-days: 7

  download-artifact:
    if: github.event.pull_request.merged == true
    needs: zip-src
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o zip-src gerado
        uses: actions/download-artifact@v8
        with:
          name: src-${{ github.event.pull_request.merge_commit_sha }}
          path: downloaded-artifact

  docker-run:

    needs: download-artifact
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Baixar artifact novamente
        uses: actions/download-artifact@v8
        with:
          name: src-${{ github.event.pull_request.merge_commit_sha }}
          path: downloaded-artifact

      - name: Substituir src pela versão do artifact
        run: |
          rm -rf src
          cp -r downloaded-artifact src

      - name: Mostrar estrutura final
        run: ls -R

      - name: Build da imagem Docker
        run: docker build -t batalha-java .

      - name: Rodar container Docker
        run: docker run --rm batalha-java